name: Automation

on:
  push:
    branches:
    - main
  issues:
    types: [opened]
  pull_request:
    types: [opened, reopened, synchronize]
env:
  MY_GITHUB_TOKEN: ${{ secrets.GHBOT_TOKEN }}

jobs:
  projectassignment:
    runs-on: ubuntu-latest
    name: Add to Terraform project
    steps:
    - name: If opened, add to project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/crayon/projects/2'
  releasedraft:
    runs-on: ubuntu-latest
    name: Update release draft
    steps:
    - uses: release-drafter/release-drafter@v5.15.0
      env:
        MY_GITHUB_TOKEN: ${{ secrets.GHBOT_TOKEN }}
